---
header: |
  # frozen_string_literal: true

  require "simplecov"

  ::SimpleCov.command_name "Brutal test suite"
  ::SimpleCov.start

  require "./lib/pseudo_legal_move_tablebase/shogi"

subject: |
  PseudoLegalMoveTablebase::%{chess_variant}::DB

contexts:
  chess_variant: Shogi

actuals:
  - "%{subject}.keys"
